# Generated by Django 4.1.7 on 2023-03-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_session_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watches',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
