# Generated by Django 4.1.7 on 2023-03-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_video_watches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='watches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
